version: "3.8"
services:
  jbc-validator:
    container_name: jbc-validator
    image: sigp/lighthouse
    user: root
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./config:/config
    command:
      - lighthouse
      - vc
      - --beacon-nodes=${PUBLIC_BEACON_NODE}
      - --testnet-dir=/config
      - --init-slashing-protection
      - --graffiti=${NODE_GRAFFITI}
      - --suggested-fee-recipient=0x53D1644eE7d5c3BF830B2E13163f99B90bf34b93
      - --debug-level=info